### ISSUE TITLE
ReferenceError: URL is not defined

### ISSUE THREAD

**Issue by slaveofcode** [criblio/js2bin#10]
I Got error `ReferenceError: URL is not defined` when build for linux 
```
2019-07-10T04:23:35.554Z - building for version=10.16.0, plat=linux app=/home/aditya/GCI/dev/pigeon/server.js}
2019-07-10T04:23:35.556Z - downloading https://github.com/criblio/js2bin/releases/download/v1.0.4/linux-x64-10.16.0-v1-2MB to /home/aditya/GCI/dev/pigeon/cache/linux-x64-10.16.0-v1-2MB ...
(node:4412) UnhandledPromiseRejectionWarning: ReferenceError: URL is not defined
    at Promise (/home/aditya/.nvm/versions/node/v8.13.0/lib/node_modules/js2bin/src/util.js:132:18)
    at new Promise (<anonymous>)
    at download (/home/aditya/.nvm/versions/node/v8.13.0/lib/node_modules/js2bin/src/util.js:124:10)
    at NodeJsBuilder.downloadCachedBuild (/home/aditya/.nvm/versions/node/v8.13.0/lib/node_modules/js2bin/src/NodeBuilder.js:103:12)
    at NodeJsBuilder.buildFromCached (/home/aditya/.nvm/versions/node/v8.13.0/lib/node_modules/js2bin/src/NodeBuilder.js:224:17)
    at p.then (/home/aditya/.nvm/versions/node/v8.13.0/lib/node_modules/js2bin/js2bin.js:99:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
(node:4412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:4412) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by ledbit** [comment]
what (local) version of `node` are you using? can you try with 10.x?

**Comment by slaveofcode** [comment]
Hi @ledbit, already use the `10.x` version, but now I got the different errors 

```
2019-07-11T05:13:52.634Z - building for version=10.13.0, plat=linux app=/home/aditya/GCI/dev/pigeon/server.js}
2019-07-11T05:13:52.639Z - downloading https://github.com/criblio/js2bin/releases/download/v1.0.4/linux-x64-10.13.0-v1-2MB to /home/aditya/GCI/dev/pigeon/cache/linux-x64-10.13.0-v1-2MB ...
(node:5389) UnhandledPromiseRejectionWarning: Error: Non-OK response, statusCode=404, url=https://github.com/criblio/js2bin/releases/download/v1.0.4/linux-x64-10.13.0-v1-2MB
    at ClientRequest.proto.request (/home/aditya/.nvm/versions/node/v10.13.0/lib/node_modules/js2bin/src/util.js:156:23)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:555:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:441:20)
    at TLSSocket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at TLSSocket.Readable.push (_stream_readable.js:219:10)
(node:5389) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5389) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
``` 

From the line error I saw the process is downloading some binary from github releases 

> ...downloading https://github.com/criblio/js2bin/releases/download/v1.0.4/linux-x64-10.13.0-v1-2MB 

So I try to install `10.16` version which available on releases item. And it works!

From my perspective, I think the supporten version of node should be listed in README.

**Comment by ledbit** [comment]
hey @slaveofcode there is an issue filed for notifying users that a prebuilt binary for a particular version is not available and be able to fallback to build from source. See #6
